name       : kamera
version    : 17.12.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/kamera-17.12.1.tar.xz : b626ceb0bb32c52dd1c4da55a77b645923340f6e523e4469e2ee41cecc15faa6
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE integration for gphoto2 cameras
description: |
    KDE integration for gphoto2 cameras.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgphoto2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
