name       : kamera
version    : 19.08.1
release    : 26
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/kamera-19.08.1.tar.xz : 109a030ef55b941758e8d4a58b2abed4c5e1bb7e13e8d239b7132867c801acf5
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE integration for gphoto2 cameras
description: |
    KDE integration for gphoto2 cameras.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
