name       : kamera
version    : 18.04.1
release    : 10
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/kamera-18.04.1.tar.xz : 0f2af766ce1b03d5ec871ea5a79f05f2d1eacdf45997baf15fd33aa3778347e5
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
summary    : KDE integration for gphoto2 cameras
description: |
    KDE integration for gphoto2 cameras.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgphoto2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
