name       : kamera
version    : 17.12.0
release    : 5
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.0/src/kamera-17.12.0.tar.xz : 0ca4ccef0dc909ab05cced4da21138b278f050444799c8e80136374a2ef3c058
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
optimize   : lto
summary    : KDE integration for gphoto2 cameras
description: |
    KDE integration for gphoto2 cameras.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgphoto2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
