name       : kamera
version    : 17.08.2
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/kamera-17.08.2.tar.xz : 8ae596a3d0060d7e491a41ed5d8180f0b27dada5146e4d9b5969f0338c112da6
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
summary    : KDE integration for gphoto2 cameras
description: |
    KDE integration for gphoto2 cameras.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgphoto2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
