name       : kamera
version    : 17.08.1
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/kamera-17.08.1.tar.xz : c1b92568f00999590c758de36e4f3144ce4f2583f82e6b1383dd391426b09510
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
summary    : KDE integration for gphoto2 cameras
description: |
    KDE integration for gphoto2 cameras.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libgphoto2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
