name       : kamera
version    : 18.08.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/kamera-18.08.0.tar.xz : dc22b6369da23a7447462c880146ecddbb2579a1e22a068fd0bc3f766dd73b99
license    :
    - GFDL-1.2
    - GPL-2.0
component  : desktop.kde.core
summary    : KDE integration for gphoto2 cameras
description: |
    KDE integration for gphoto2 cameras.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfig-devel
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
