name       : kamera
version    : 19.12.2
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.2/src/kamera-19.12.2.tar.xz : 8ee666ed0b53cfda35344e5baa2747d36c0f6d657a8bf9582252ae97187c2f78
homepage   : https://kde.org/applications/utilities/org.kde.kamera
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : desktop.kde.core
summary    : KDE integration for gphoto2 cameras
description: |
    KDE integration for gphoto2 cameras.
builddeps  :
    - pkgconfig(libgphoto2)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
